### ISSUE TITLE
Allow "Guest" Users to Make On-Order and In Process Requests.. 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3977] opened 2024-03-14 18:58 UTC
### What maintenance needs to be done?
Currently "Guest" users in certain Alma patron groups cannot make in-process or on-order requests. They should be able to per circulation. Currently I believe what is happening is that users who have logged in with an Alma Internal Account as opposed to Single Sign-On are denied the ability to make these requests. 

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
Users cannot make requests they should be able to. 

### Acceptance criteria
 - [ ] Users from the following Alma Patron groups Affiliate-P, Affiliate, and GST can make on-order and in-process requests. 

### Implementation notes, if any
We may be able to just relax the restriction that an account must be logged in via CAS to make these requests if we want to do this prior to the large re-factor make all circ request options driven by what Alma Patron Group users are in. This is a part of ticket #3188 which would be the full implementation of the [current patron group/request service matrix](https://docs.google.com/spreadsheets/d/1c4lmMiOzSqMbPYEM5Ni2pofI8lvKpv0FlaRx-xui39E/edit?gid=0#gid=0).

**Comment by maxkadel** [comment] 2024-09-17 19:42
Closing - not able to reproduce the issue.

**Closed by maxkadel** 2024-09-17 19:42 UTC
Labels: feature
