### ISSUE TITLE
Webcrawler created params break range limit helper

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#1344] opened 2018-08-28 15:28 UTC
## Backtrace

    line 19 of [PROJECT_ROOT]/app/views/catalog/_facets.html.erb: _app_views_catalog__facets_html_erb__3257402144758604111_70009624166000
    line 5 of [PROJECT_ROOT]/app/views/catalog/index.html.erb: _app_views_catalog_index_html_erb__103655424133820930_70009624426260

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/35761476)

`ActionView::Template::Error: undefined method '>' for nil:NilClass` in 

```
range_limit_helper.rb  57 should_show_limit(...)
[GEM_ROOT]/gems/blacklight_range_limit-6.3.2/app/helpers/range_limit_helper.rb:57:in `should_show_limit'
```

**Comment by eliotjordan** [comment] 2018-08-28 15:32
Perhaps we need to filter param combinations that we know will cause exceptions?

**Comment by escowles** [comment] 2018-09-14 18:19
We should probably return a 4xx error if the client gives us bogus input.

**Comment by jrgriffiniii** [comment] 2018-10-04 18:34
https://app.honeybadger.io/projects/54399/faults/35761476 indicates that a human user triggered this more recently.

**Comment by christinach** [comment] 2018-10-04 20:50
I can't reproduce this locally.

**Comment by christinach** [comment] 2018-10-05 13:06
This has been resolved with the latest deploys on master and it will be resolved as soon as we deploy to production. This url used to return a 500 error. Testing it in catalog-staging will return a 200 response.

**Comment by jrgriffiniii** [comment] 2018-11-06 13:50
Orangelight was last deployed to the production environment on 11/01/18, and this (or a seemingly related error) is still occurring.

**Closed** 2018-12-07 20:04 UTC
Labels: bug, review
