### ISSUE TITLE
Unable to connect to Solr

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#2451] opened 2021-05-14 17:50 UTC
[Orangelight/production] Blacklight::Exceptions::ECONNREFUSED: Connection refused - Unable to connect to Solr instance using #<RSolr::Client:0x00007f9ee0e94c48 @uri=#<URI::HTTP http://lib-solr8-prod.princeton.edu:8983/solr/catalog-production/>, @proxy=nil, @connection=#<Faraday::Connection:0x00007f9ee0e94180 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.17.4"}, @params={}, @options=#<Faraday::RequestOptions params_encoder=Faraday::FlatParamsEncoder>, @ssl=#<Faraday::SSLOptions (empty)>, @def...

## Backtrace

    line 12 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/39852080)

**Comment by hackartisan** [comment] 2021-05-14 20:40
This looks like a duplicate of https://github.com/pulibrary/princeton_ansible/issues/1799; comments in the honeybadger notice also reference that ticket.

**Closed by hackartisan** 2021-05-14 20:40 UTC
