### ISSUE TITLE
Ensure that links with the same accessible name serve a similar purpose

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2797] opened 2021-11-08 19:26 UTC
impact: 

issue tags: cat.semantics, wcag2aaa, wcag249, best-practice

Element location: p > a[title="Opens\ in\ a\ new\ tab"][target="_blank"]
Element source: 
`<a href="https://library.princeton.edu/about/languagestatement" target="_blank" title="Opens in a new tab">Read more...</a>`
To solve this issue, you need to.
Check that links have the same purpose, or are intentionally ambiguous.

Related node:
Inspect node
p > a[href$="dataset"]

ACCEPTANCE CRITERIA:

- [ ] Add better description got the links. Not just 'Read more...'

**Comment by sandbergja** [comment] 2022-08-18 21:35
Closing as duplicate of #3083

**Closed by sandbergja** 2022-08-18 21:35 UTC
Labels: accessibility
