### ISSUE TITLE
Export bookmarks as CSV

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#876] opened 2017-05-10 11:37 UTC
Taking to Gabriel, would be useful for further data manipulation.

**Comment by kevinreiss** [comment] 2017-05-10 13:22
We could check the database for how heavy bookmark use is in OL but in Voyager we've had issues where staff have used that feature to be a reporting tool of sorts and tried to email themselves thousands of records. If we aren't going to arbitrarily cap the number of items that can be exported we are probably looking at an asynchronous method to generate and deliver the CSV.

**Comment by jpstroop** [comment] 2017-05-10 13:33
Async and a mailer would probably be a good idea--that sounds exactly like his use case.

**Comment by escowles** [comment] 2018-12-03 21:58
Closing as dupe of #1467

**Closed by escowles** 2018-12-03 21:58 UTC
