### ISSUE TITLE
QA Environment Produces 500 Error Whenever an action Involving Email Is Taken

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#4533] opened 2024-11-05 17:54 UTC
### Actual behavior
Include screenshots, or links and browser version if relevant

### Steps to replicate
1. Add some bookmarks to your account in QA
2. Visit the bookmarks page and select the email control option. You'll get thee 500 error at https://catalog-qa.princeton.edu/bookmarks/email when you submit the modal that comes up when select "email."

### Impact of this bug
It's only QA. 

### Honeybadger link and code snippet, if applicable
```Net::SMTPServerBusy: 454 4.7.1 <kr2@princeton.edu>: Relay access denied ```
See https://app.honeybadger.io/projects/54399/faults/114351531

### Implementation notes, if any
We should either allow mail in QA or ensure that mail catcher grabs the message so the interface does not permit an error.

**Comment by kevinreiss** [comment] 2024-11-05 20:56
Note this also causes the request form submit button to fail. https://app.honeybadger.io/projects/54399/faults/113222385

**Comment by maxkadel** [comment] 2024-11-06 18:43
Duplicate of https://github.com/pulibrary/princeton_ansible/issues/5410

**Closed by maxkadel** 2024-11-06 18:43 UTC
Labels: bug
