### ISSUE TITLE
Different default font needed for Devanagari Script

### ISSUE THREAD

**Issue by tventimi** [pulibrary/orangelight#3609] opened 2023-06-15 13:03 UTC
### Expected behavior
Devanagari (Hindi) script should be displayed with a font that renders ligatures correctly.  The Columbia catalog does this.  See, for example the first word of the title in this record:
https://clio.columbia.edu/catalog/12826630?counter=2
![image](https://github.com/pulibrary/orangelight/assets/9369786/9c735fb6-3c16-4808-a043-bb340ba9b486)

### Actual behavior
In the Princeton record for the same item, a small tick mark appears below the word at about the halfway point.  This is incorrect (and is a good indicator in general that the ligatures are not displaying correctly):
https://catalog.princeton.edu/catalog/99102083273506421
![image](https://github.com/pulibrary/orangelight/assets/9369786/6a752a7f-9473-49a6-b0f9-b659bfa7bebb)

### Steps to replicate
The contrast can be seen by opening both records in a browser.  I was able to see the difference right away in Edge and Chrome.  But in Firefox, I first had to go into the font settings and check "Allow pages to choose their own fonts".  

### Impact of this bug
This bug is not an obstacle to any workflow, and the text is still readable, but in its current form is not the preferred "spelling" of the Hindi word.  This would be evident to those familiar with this script.

### Implementation Notes
The text in question appears correctly in Alma.  So, the issue just has to do with how the text is rendered in Blacklight, not the underlying data.  The default font set used by the Columbia catalog is "Helvetica Neue, Helvetica, Arial, sanf-serif".  The default font set used by Blacklight is "DjVu Sans, Arial Unicode MS, Helvetica, sans-serif".  If I use the browser's "developer tools" to manually change the fonts used by Blacklight to match the ones used by Columbia, then the text renders correctly.

**Comment by maxkadel** [comment] 2023-06-19 15:17
The team has not been able to replicate this issue - follow-up with @tventimi.

**Comment by sandbergja** [comment] 2023-06-20 22:22
@kelea99 pointed us toward a similar ticket here: https://github.com/pulibrary/dpul/issues/1417

**Comment by maxkadel** [comment] 2023-06-29 19:08
Checked in with Tom, it seems like the issue is the now-deprecated "Arial Unicode MS", which we should replace with a different font.

**Comment by maxkadel** [comment] 2023-06-30 13:18
Closed by https://github.com/pulibrary/orangelight/pull/3626. Deployed to production 6/30/2023

**Closed by maxkadel** 2023-06-30 13:18 UTC
Labels: investigate
