### ISSUE TITLE
[Requests] NoMethodError: undefined method `errors' for #<Array:0x00007f0fb80fbb98>

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2938] opened 2022-04-08 17:16 UTC
In 
app/models/requests/selected_items_validator.rb:72
```
70   item_id = selected['item_id']
71          if selected["delivery_mode_#{item_id}"].nil?
72            record.errors[:items] << { item_id => { 'text' => 'Please select a delivery type for your 
  selected recap item', 'type' => 'options' } }
73        else
          delivery_type = selected["delivery_mode_#{item_id}"]
```
See honeybadger error: https://app.honeybadger.io/projects/54399/faults/84903108

`POST https://catalog.princeton.edu/requests/submit.js`
https://catalog.princeton.edu/requests/SCSB-5117153

**Comment by rladdusaw** [comment] 2022-08-08 14:32
Duplicate of #3052?

**Comment by sandbergja** [comment] 2022-08-08 16:07
closing as duplicate

**Closed by sandbergja** 2022-08-08 16:07 UTC
Labels: maintenance
