### ISSUE TITLE
Ensuring proper list structure aids screen reader output.

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2801] opened 2021-11-09 01:11 UTC
**Search results page**

Lists do not contain only elements and script supporting elements (<script> and <template>).
Screen readers have a specific way of announcing lists. 
Ensuring proper list structure aids screen reader output. https://web.dev/list/?utm_source=lighthouse&utm_medium=devtools

Fix the following:
List element has direct children that are not allowed inside <li> elements

Related node:
abbr[title="\39 9125289673606421"]

**Comment by sandbergja** [comment] 2022-08-18 16:14
Closing as duplicate of #1063

**Closed by sandbergja** 2022-08-18 16:14 UTC
Labels: accessibility
