### ISSUE TITLE
find a better place for Other Library Resources on home page

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#577] opened 2016-06-03 13:05 UTC
Users thought these were how to start using the application. related to #576

**Comment by axamei** [comment] 2016-06-06 13:43
Move it to the right of the welcome message or push it down to the footer? There are some identical links under the "Research Tools" section in the footer.

**Comment by tampakis** [comment] 2016-06-07 20:35
Duplicate of #584

**Closed by tampakis** 2016-06-07 20:35 UTC
