### ISSUE TITLE
change availability display from "unavailable" to "online" for permanent CDL microfilm in Figgy

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/orangelight#3337] opened 2023-01-03 19:09 UTC
### User story
from https://faq.library.princeton.edu/admin/ticket?qid=9414780: 

Hi E-support:

With regard to digitized microfilm in Figgy that is permanently CDL – (example: https://catalog.princeton.edu/catalog/99125464716806421), after searching for the item, the first screen visible to the user says the item is Unavailable, when, in actuality, it is available digitally. In these situations, is it possible to change the wording from Unavailable to something else such as: Online ?

Thanks,

Joann

**Comment by christinach** [comment] 2023-01-05 03:11
duplicate of https://github.com/pulibrary/orangelight/issues/2995

**Closed by christinach** 2023-01-05 03:11 UTC

**Comment by ellen-aa** [comment] 2024-08-06 14:28
The results page is misleading for a user. Instead of displaying "Unavailable" or "Online", could this display "Available for digital checkout"? See ticket #2995.
