### ISSUE TITLE
NoMethodError in errors # error

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/orangelight#3068] opened 2022-07-13 21:07 UTC
https://app.honeybadger.io/projects/54399/faults/86723612

[PROJECT_ROOT]/app/models/requests/patron.rb:217:in `build_cas_patron'
215 |  
216 | patron_resource = JSON.parse(api_response.body)
217 | patron_resource.with_indifferent_access
218 | end
219 | end

**Comment by christinach** [comment] 2022-07-25 17:31
duplicate of #3054

**Closed by christinach** 2022-07-25 17:31 UTC
