### ISSUE TITLE
Form submit control for searchbox is problematic on mobile

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#2346] opened 2021-01-13 22:51 UTC
![Screenshot_20210113-174845](https://user-images.githubusercontent.com/999701/104519681-d4aea400-55c7-11eb-9528-89fdb98c31db.png)

**Comment by axamei** [comment] 2021-03-21 14:14
Also seeing issues on the record page:
![image](https://user-images.githubusercontent.com/8161144/111908043-13c8fd80-8a2e-11eb-8e0f-18889a4c553e.jpeg)

**Comment by kevinreiss** [comment] 2023-01-03 16:57
Needs to become part of an EPIC on mobile display issues.

**Comment by christinach** [comment] 2023-12-01 00:52
duplicate of https://github.com/pulibrary/orangelight/issues/2174

**Closed** 2023-12-01 14:36 UTC
Labels: interface, user experience
