### ISSUE TITLE
Allow users to expand coin references

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/orangelight#2044] opened 2020-05-19 22:02 UTC
### Current display
References are currently displayed in their short-form.

### Desired display
- [ ] Index the full form and display when the user clicks the reference (or maybe hover?)
- [ ] Allow users to link to the catalog record for the reference, if it exists

### Acceptance criteria
- - [ ] Index the full form and display when the user clicks the reference (or maybe hover?)
- [ ] Allow users to link to the catalog record for the reference, if it exists
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave
- [ ] ...

**Comment by christinach** [comment] 2023-04-06 14:19
Related or duplicate of to https://github.com/pulibrary/orangelight/issues/2785

**Comment by christinach** [comment] 2023-04-06 14:20
@kelea99 can we confirm if #2785 and this issue #2044 are the same?

**Comment by christinach** [comment] 2023-04-06 15:56
duplicate of https://github.com/pulibrary/orangelight/issues/2785

**Closed by christinach** 2023-04-06 15:56 UTC
Labels: numismatics

**Comment by caroldh** [comment] 2024-08-01 16:00
@christinach 
This is a duplicate of #2785 - we should close this one unless there is some reason to keep it open?
