### ISSUE TITLE
Don't show me option to change my PW if I'm logged in w/ CAS

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#211] opened 2015-08-19 20:59 UTC
This page needs some love.

![cas](https://cloud.githubusercontent.com/assets/999701/9368820/98be1afa-4693-11e5-9fbf-57711823e3a6.png)

**Comment by tampakis** [comment] 2015-08-19 21:00
Duplicate of #171

**Closed by tampakis** 2015-08-19 21:00 UTC
