### ISSUE TITLE
When submitting an Advanced Search a "constraint-value" is not created on the search results page.

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3703] opened 2023-08-25 20:30 UTC
When using Blacklight 8 and starting a search from advanced search a "constraint-value" is not created on the search results page this is true for both regular advanced search and the Numismatics search. 

To Replicate
1. Pin your blacklight to https://github.com/projectblacklight/blacklight/tree/release-7.x
2. Activate JSON DSL Flipper
3. Active new Advanced Search Form Flipper
4. Go to the advanced search form and run a search
5. On the search results page you will not see any constraint values displayed. The "Cats" with the x in the screenshot below is missing

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3hTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4e5f839dd437fa302b4de54cdafd6f2767550f5e/Screenshot%202023-08-30%20at%2010.20.03%20AM.png)

Also see #3700

**Comment by christinach** [comment] 2023-09-06 15:12
@rladdusaw cannot reproduce this error.

**Comment by maxkadel** [comment] 2023-09-06 20:20
Still present on main

**Comment by maxkadel** [comment] 2023-09-06 21:06
There is a test that should be failing for the right reason in [spec/features/advanced_searching_spec.rb](https://github.com/pulibrary/orangelight/blob/main/spec/features/advanced_searching_spec.rb#L108-L117), it's currently marked as pending, and when the bug is resolved it should start failing (or, if you're working on this, just take out the "pending")

**Closed** 2023-09-07 16:48 UTC
Labels: bug
