### ISSUE TITLE
CSS problems on mobile

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#2345] opened 2021-01-13 22:51 UTC
![Screenshot_20210113-174845](https://user-images.githubusercontent.com/999701/104519681-d4aea400-55c7-11eb-9528-89fdb98c31db.png)

**Comment by kevinreiss** [comment] 2023-01-03 19:50
duplicate of 2346

**Closed by kevinreiss** 2023-01-03 19:50 UTC
