### ISSUE TITLE
NoMethodError: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/orangelight#2395] opened 2021-04-05 18:52 UTC
[Orangelight/production] NoMethodError: undefined method `each' for nil:NilClass

## Backtrace

    line 12 of [PROJECT_ROOT]/lib/orangelight/middleware/invalid_parameter_handler.rb: call

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54399/faults/39793242)

More backtrace:

request_controller.rb  104  sanitize_submission(...)
```

102 |  
-- | --
103 | def sanitize_submission(params)
104 | params[:requestable].each do \|requestable\|
105 | params['user_supplied_enum'] = sanitize(requestable['user_supplied_enum']) if requestable.key? 'user_supplied_enum'
106 | end


```

**Comment by hectorcorrea** [comment] 2021-06-07 20:43
The error message in Honeybadger says "NoMethodError: undefined method `with_indifferent_access' for nil:NilClass" for this URL: https://catalog.princeton.edu/requests/1873599?mfhd=1873599&source=firestone_locator1873599

This seems caused due to lack of validation in the Requests app, from the Honeybadger stacktrace it seems that the issue is in [build_requestable_from_data](https://github.com/pulibrary/requests/blob/main/app/models/requests/request.rb#L250-L255)

```
def build_requestable_from_data
        return if doc[:holdings_1display].nil?
        @mfhd ||= 'thesis' if thesis?
        @mfhd ||= 'numismatics' if numismatics?
        [build_requestable_from_holding(@mfhd, holdings[@mfhd].with_indifferent_access)]
end
```

My guess is that the `mfdh` is not valid and that's why `holdings[@mfhd].with_indifferent_access` throws an error.

**Comment by kevinreiss** [comment] 2021-06-07 20:54
This record is in ETAS, https://catalog.princeton.edu/catalog/1873599 so no one should be requesting it or being referred by any of our applications to request it at the moment. I see the book locator is created the URL that generated the error, this is old functionality that we should remove when we circle back to updating it for alma. 
https://catalog.princeton.edu/requests/1873599?mfhd=1873599&source=firestone_locator1873599.

**Comment by hackartisan** [comment] 2021-06-08 13:09
@kevinreiss could you update the title of this issue to reflect what needs to be done based on your analysis? I think that will make it easier to keep track of. 

I went ahead and copied the original title into the description so it's still easy to see.

**Comment by hectorcorrea** [comment] 2021-08-09 15:18
Please be aware that this error has morphed, perhaps because we are now live with Alma? 

The most [recent instances reported in Honeybadger](https://app.honeybadger.io/projects/54399/faults/39793242) show:

```
NoMethodError: undefined method `errors' for #<Array:0x00007ff4e8af5098>
```

**Comment by kevinreiss** [comment] 2022-03-10 04:15
https://catalog.princeton.edu/requests/9915946413506421?mfhd=22538008330006421

**Comment by sandbergja** [comment] 2022-03-11 22:06
The current incarnation of the issue appears to be in the requests gem, so I'm closing this ticket in favor of https://github.com/pulibrary/requests/issues/1120

**Closed by sandbergja** 2022-03-11 22:06 UTC
