### ISSUE TITLE
Generate sitemap for bots

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/orangelight#525] opened 2016-05-16 14:09 UTC
Explore https://github.com/jronallo/blacklight-sitemap. Does it still work? Jasson seems open to a PR if it doesn't.

How often can we generate? If it's fast enough we can do nightly after the updates. Otherwise a wider interval might make more sense.

**Comment by escowles** [comment] 2017-12-07 20:08
Closing dupe of #1000

**Closed by escowles** 2017-12-07 20:08 UTC
