### ISSUE TITLE
User should not have to click 2 login links

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/orangelight#2446] opened 2021-05-13 14:09 UTC
On the bookmarks page, click "login". You then have to click another login button to actually enter your information.

It would be nice to embed these choices in the bookmarks and search history pages directly. See https://github.com/pulibrary/orangelight/pull/2444#issuecomment-839872031 for a wireframe.

**Comment by bess** [comment] 2021-09-30 19:48
This is a duplicate of #2709

**Closed by bess** 2021-09-30 19:48 UTC
Labels: user experience, duplicate
