### ISSUE TITLE
Facets are being duplicated when editing advanced search

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/orangelight#4228] opened 2024-09-05 15:19 UTC
### Expected behavior
When I edit an advanced search, the already selected facets are maintained and not duplicated.

### Actual behavior
The facet contains the block with the text "Any of: [selected facet value]" twice.

### Steps to replicate
In the advanced search select a facet like Access: In the library, click search.
Once the search loads click Edit Search to go back to the search form.
Click Search again and you will see the duplicated element.

### Impact of this bug
Visual bug that clutters up the UI

**Comment by christinach** [comment] 2024-09-10 15:15
duplicate of https://github.com/pulibrary/orangelight/issues/3384

**Closed by christinach** 2024-09-10 15:15 UTC
Labels: bug
