### ISSUE TITLE
Random format:journal result after clicking 'Back to Search'

### ISSUE THREAD

**Issue by christinach** [pulibrary/orangelight#2726] opened 2021-09-14 14:43 UTC
Reported from two users in the catalog channel:
It is not consistent.
The user is logged in the catalog.
Search for a keyword: 'math' -> get results -> click on a record -> click 'back to search' -> will redirect the user to https://catalog.princeton.edu/?f%5Bformat%5D%5B%5D=Journal&page=1&per_page=20

This issue might be related to https://github.com/pulibrary/orangelight/issues/2720 

**ACCEPTANCE CRITERIA**
- [ ] I click "back to search" and it has not added any extra search criteria (e.g., "Format:Journal")

**Comment by hectorcorrea** [comment] 2021-09-17 13:51
See video provided by Minje on how to reproduce this error:

https://princeton.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=10070e41-8882-4ade-a608-ada600dd0d64

Notice that when she refreshes the page on an individual record the number of records changes to exactly the numnber of records in the "Format: Journal" facet, meaning at that point the session information has changed.

**Comment by hectorcorrea** [comment] 2021-09-28 13:27
We cannot reproduce this issue and neither can Minje. We tried with Chrome and Firefox, logged-in and not logged-in to no avail. I am closing the issue for now and we'll look into it again if/when it happens again.

**Closed by hectorcorrea** 2021-09-28 13:27 UTC
Labels: bug
