### ISSUE TITLE
Record in Annex with No Items Tries to Place a Hold Request

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#3980] opened 2024-03-19 13:58 UTC
### Expected behavior
Records with no items cannot have Alma hold requests created.
Records with no items should allow the user to specify details about the volume they want and send an email to circ staff telling the staff the details of the users request . 

### Actual behavior
When submitting the form you see:

<img width="1517" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0R4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--95b6fcf3cc29160dd134d91e49a1c9c0de757568/Screenshot%202024-03-19%20at%208.57.02%E2%80%AFAM.png" alt="Screenshot 2024-03-19 at 8.57.02 AM.png" />

### Steps to replicate
Visit https://catalog.princeton.edu/catalog/9947608733506421
Click Request
Select Physical Item Delivery and pick a delivery locaiton 

Try to request the item
This generates an alma hold request error notification sent to recapproblems for triage. 

### Impact of this bug
Users can't request an record with no items. 

### Honeybadger link and code snippet, if applicable
Alma error is ```Hold can not be created, message: Invalid Response.```. 

### Implementation notes, if any
Investigate to see if this a widespread issue.

**Comment by christinach** [comment] 2024-09-11 15:22
duplicate of https://github.com/pulibrary/orangelight/issues/4183

**Closed by christinach** 2024-09-11 15:22 UTC
Labels: bug
