### ISSUE TITLE
Use Solr document fields in the open url

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/orangelight#218] opened 2015-08-24 17:55 UTC
http://pulsearch-dev.princeton.edu/catalog/9026021 has two ISBNs attached to it but the OpenURL created for the "COINS" template has a blank rft.isbn parameter in it. Need to audit the code that creates this to make sure it reliably includes ISBN's when they are present.

Current Output:

```
<span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rfr_id=info%3Asid%2Fblacklight.rubyforge.org%3Agenerator&amp;rft.genre=book&amp;rft.btitle=The+next+justice+repairing+the+Supreme+Court+appointments+process+%2F&amp;rft.title=The+next+justice+repairing+the+Supreme+Court+appointments+process+%2F&amp;rft.au=Eisgruber%2C+Christopher+L.&amp;rft.date=c2007.&amp;rft.place=Princeton+%3A&amp;rft.pub=Princeton+University+Press%2C&amp;rft.edition=&amp;rft.isbn=&amp;rft_id=pul_9026021"></span>
```

**Comment by kevinreiss** [comment] 2015-08-24 17:57
The alternative format displayed in the document's head 

```
<link rel="alternate" title="openurl_ctx_kev" type="application/x-openurl-ctx-kev" href="http://pulsearch-dev.princeton.edu/catalog/9026021.openurl_ctx_kev">
```

also produces a slightly different OpenURL. We should probably get them in sync.

**Comment by tampakis** [comment] 2015-09-01 14:44
There are two issues here, which we should discuss at the meeting today. 
 - For this record both of the isbns are in $z, which means that the ISBN is [obsolete](https://www.loc.gov/marc/bibliographic/bd020.html). The parameter is blank because it grabs the 020 $a from the Marc.
 - I think we should pass the parameter the normalized isbn value from the isbn field rather than extract it from the marc.

**Comment by kevinreiss** [comment] 2016-05-23 18:34
@tampakis @jpstroop we received a feedback comment asking for zotero support on the search results page that is related to this open issue. Zotero will scrape all ctx span tags (shown in the initial comment on this thread) embedded on a page as individual citations. We could extend the index view to include a ctx span with an OpenURL for each hit as a means to support this request. 

However, the code that we have which generates the ctx spans that appears on the "show" page is pretty crufty (and inefficient), see https://github.com/pulibrary/orangelight/blob/development/config/initializers/blacklight_initializer.rb. I tried out embedding this routine on index page at one point and it was really slow. This code has now been moved over to blacklight-marc now but it has been unchanged for quite awhile. I'm thinking we should return to the idea of creating an OpenURL for each record than can be stored in the solr doc at index time. We can then use this data for the purpose of generating ctx spans on both the index and show views. Having an OpenURL around would also be useful for portions of the requests system.

**Comment by jpstroop** [comment] 2016-12-07 20:59
Is this a dupe of #256?

**Comment by tampakis** [comment] 2016-12-07 21:11
I think there might be some useful info in the comments but now that you made the link we are fine. Also I don't think we need to take this approach anymore of using the openurl for citation management, but I think it's important to spend some time reviewing this.

**Closed** 2017-01-30 11:38 UTC
Labels: feedback, in progress, record display
